/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ApplicationQuery: typeof import('./src/components/ApplicationQuery.vue')['default']
    ExcelExport: typeof import('./src/components/ExcelExport.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MaterialApplicationForm: typeof import('./src/components/MaterialApplicationForm.vue')['default']
    PackagingFormSection: typeof import('./src/components/PackagingFormSection.vue')['default']
    PackagingSection: typeof import('./src/components/PackagingSection.vue')['default']
    PackagingTemplateSettings: typeof import('./src/components/PackagingTemplateSettings.vue')['default']
    ReviewManagement: typeof import('./src/components/ReviewManagement.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemSettings: typeof import('./src/components/SystemSettings.vue')['default']
  }
}
