/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AggregatedField: typeof import('./src/components/form-fields/AggregatedField.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ApplicationQuery: typeof import('./src/components/ApplicationQuery.vue')['default']
    ApprovalWorkflowSettings: typeof import('./src/components/ApprovalWorkflowSettings.vue')['default']
    CascadingSelectField: typeof import('./src/components/form-fields/CascadingSelectField.vue')['default']
    CascadingSelectLevel: typeof import('./src/components/form-fields/CascadingSelectLevel.vue')['default']
    CheckboxField: typeof import('./src/components/form-fields/CheckboxField.vue')['default']
    DateField: typeof import('./src/components/form-fields/DateField.vue')['default']
    DatetimeField: typeof import('./src/components/form-fields/DatetimeField.vue')['default']
    DynamicFormRenderer: typeof import('./src/components/DynamicFormRenderer.vue')['default']
    ExcelExport: typeof import('./src/components/ExcelExport.vue')['default']
    FileField: typeof import('./src/components/form-fields/FileField.vue')['default']
    FormDesigner: typeof import('./src/components/FormDesigner.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    JsonField: typeof import('./src/components/form-fields/JsonField.vue')['default']
    MaterialApplicationForm: typeof import('./src/components/MaterialApplicationForm.vue')['default']
    MaterialApplicationFormDemo: typeof import('./src/components/MaterialApplicationFormDemo.vue')['default']
    MultiselectField: typeof import('./src/components/form-fields/MultiselectField.vue')['default']
    NumberField: typeof import('./src/components/form-fields/NumberField.vue')['default']
    PackagingFormSection: typeof import('./src/components/PackagingFormSection.vue')['default']
    PackagingSection: typeof import('./src/components/PackagingSection.vue')['default']
    PackagingTemplateSettings: typeof import('./src/components/PackagingTemplateSettings.vue')['default']
    RadioField: typeof import('./src/components/form-fields/RadioField.vue')['default']
    ReviewManagement: typeof import('./src/components/ReviewManagement.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectField: typeof import('./src/components/form-fields/SelectField.vue')['default']
    SystemSettings: typeof import('./src/components/SystemSettings.vue')['default']
    TextareaField: typeof import('./src/components/form-fields/TextareaField.vue')['default']
    TextField: typeof import('./src/components/form-fields/TextField.vue')['default']
  }
}
